# Compare tool from Stamen's Maperture project:
# https://github.com/stamen/maperture
# But Brandon's public fork on GH, which is pulled
# in at runtime to allow JSON configs of the styles.
# Requires recent version of Node.js installed (eg v16.19.1)
# Use Node Version Manager (nvm) if you have multiple version
# https://daily.dev/blog/how-to-use-multiple-node-versions-with-nvm-on-macos-node-version-manager
# Preview on http://localhost:3857/
all:
	npm run serve